### PR TITLE
Add width argument for vector mode

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
@tgymnich @wsmoses even with the ABI fix, Enzyme.jl is triggering a segmentation fault

```

signal (11): Segmentation fault
in expression starting at /home/runner/work/Enzyme.jl/Enzyme.jl/test/abi.jl:4
_ZNKSt6vectorIiSaIiEE4sizeEv at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt6vectorIiSaIiEEC1ERKS1_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt4pairIKSt6vectorIiSaIiEE12ConcreteTypeEC1ERKS5_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKSt6vectorIiSaIiEE12ConcreteTypeEEE9constructIS8_JRKS8_EEEvPT_DpOT0_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKSt6vectorIiSaIiEE12ConcreteTypeEEEE9constructIS7_JRKS7_EEEvRS9_PT_DpOT0_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt8_Rb_treeIKSt6vectorIiSaIiEESt4pairIS3_12ConcreteTypeESt10_Select1stIS6_ESt4lessIS3_ESaIS6_EE17_M_construct_nodeIJRKS6_EEEvPSt13_Rb_tree_nodeIS6_EDpOT_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt8_Rb_treeIKSt6vectorIiSaIiEESt4pairIS3_12ConcreteTypeESt10_Select1stIS6_ESt4lessIS3_ESaIS6_EE14_M_create_nodeIJRKS6_EEEPSt13_Rb_tree_nodeIS6_EDpOT_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNKSt8_Rb_treeIKSt6vectorIiSaIiEESt4pairIS3_12ConcreteTypeESt10_Select1stIS6_ESt4lessIS3_ESaIS6_EE11_Alloc_nodeclIRKS6_EEPSt13_Rb_tree_nodeIS6_EOT_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt8_Rb_treeIKSt6vectorIiSaIiEESt4pairIS3_12ConcreteTypeESt10_Select1stIS6_ESt4lessIS3_ESaIS6_EE13_M_clone_nodeINSC_11_Alloc_nodeEEEPSt13_Rb_tree_nodeIS6_EPKSG_RT_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt8_Rb_treeIKSt6vectorIiSaIiEESt4pairIS3_12ConcreteTypeESt10_Select1stIS6_ESt4lessIS3_ESaIS6_EE7_M_copyINSC_11_Alloc_nodeEEEPSt13_Rb_tree_nodeIS6_EPKSG_PSt18_Rb_tree_node_baseRT_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt8_Rb_treeIKSt6vectorIiSaIiEESt4pairIS3_12ConcreteTypeESt10_Select1stIS6_ESt4lessIS3_ESaIS6_EE7_M_copyINSC_11_Alloc_nodeEEEPSt13_Rb_tree_nodeIS6_ERKSC_RT_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt8_Rb_treeIKSt6vectorIiSaIiEESt4pairIS3_12ConcreteTypeESt10_Select1stIS6_ESt4lessIS3_ESaIS6_EE7_M_copyERKSC_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt8_Rb_treeIKSt6vectorIiSaIiEESt4pairIS3_12ConcreteTypeESt10_Select1stIS6_ESt4lessIS3_ESaIS6_EEC1ERKSC_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZNSt3mapIKSt6vectorIiSaIiEE12ConcreteTypeSt4lessIS3_ESaISt4pairIS3_S4_EEEC1ERKSA_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_ZN8TypeTreeC1ERKS_ at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_Z7eunwrapP14EnzymeTypeTree at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
_Z7eunwrap11CFnTypeInfoPN4llvm8FunctionE at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
EnzymeCreateForwardDiff at /home/runner/.julia/scratchspaces/7cc45869-7501-5eee-bdea-0790c847d4ef/build/Enzyme/libEnzyme-11.so (unknown line)
EnzymeCreateForwardDiff at /home/runner/work/Enzyme.jl/Enzyme.jl/src/api.jl:119
enzyme! at /home/runner/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:2121
unknown function (ip: 0x7f2b213e4845)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
#codegen#45 at /home/runner/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:2694
codegen##kw at /home/runner/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:2528 [inlined]
_thunk at /home/runner/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:3041
unknown function (ip: 0x7f2b4de3d601)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
cached_compilation at /home/runner/.julia/packages/GPUCompiler/1Ajz2/src/cache.jl:90
thunk at /home/runner/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:3094
fwddiff at /home/runner/work/Enzyme.jl/Enzyme.jl/src/Enzyme.jl:296
```

**Comment by tgymnich** [comment]
Which version of Enzyme are you using?

**Comment by tgymnich** [comment]
I guess I didn't consider the thunk in my patch....

**Comment by wsmoses** [comment]
Investigating now

**Comment by wsmoses** [comment]
Reproduced locally

**Pull request merged**
